#!/usr/bin/env python3
import os
import sys
from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored
def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets name")
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    s=get_user_timeline(sys.argv[1],50)
    for t in s:
        score = analyzer.analyze(t)
        if score > 0.0:
            print(colored(t, "green"))
        elif score < 0.0:
            print(colored(t, "red"))
        else:
            print(colored(t, "yellow"))

if __name__ == "__main__":
    main()

